---
name: CI - Rust tests

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Run Rust tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache Rust assets
        id: rust-cache
        uses: Swatinem/rust-cache@v2
      - name: Configure Rust
        if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.76.0
          profile: minimal
          components: clippy,rustfmt
          override: true
          target: x86_64-unknown-linux-musl
          default: true

      - name: Install Cross
        if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
        run: cargo install --locked cross

      - name: Run Linux-targeted tests of Mjolnir
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target=x86_64-unknown-linux-musl
          use-cross: true

      - name: Run Linux-targeted checks of Mjolnir
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target=x86_64-unknown-linux-musl
          use-cross: true

      - name: Run Linux-targeted Clippy tests of Mjolnir
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target=x86_64-unknown-linux-musl
          use-cross: true
