---
name: CI tests (Nix)

on:
  workflow_call:

jobs:
  run-tests:
    name: Nix CI tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - run: nix profile install tarball+https://install.devenv.sh/latest
      - name: Build Nix package
        run: nix build
      - name: Check Flake with Nix
        run: nix flake check
      - name: Test `devenv` and run hooks.
        run: devenv test
