---
name: CI - Nix tests

on:
  workflow_call:

jobs:
  run-tests:
    name: Nix CI tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
      - run: nix profile install --accept-flake-config nixpkgs#devenv
      - name: Build Nix package
        run: nix build -L
      - name: Check Flake with Nix
        run: nix flake check
      - name: Test `devenv` and run hooks.
        run: devenv test
